baseURL = 'https://trajchekrstev.github.io/lkm-site/'
languageCode = 'en-us'
title = 'LKM site'
theme = "site-theme"
paginate = 3
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Members"
    url = "/members/"
    weight = 2

